import { themeQuartz } from "ag-grid-community"

export const marketGridTheme = themeQuartz.withParams({
  accentColor: "#00A2FF",
  backgroundColor: "#000000",
  borderColor: "#108FFF",
  borderRadius: 0,
  browserColorScheme: "dark",
  cellHorizontalPaddingScale: 0.8,
  cellTextColor: "#108FFF",
  columnBorder: true,
  fontFamily: "var(--font-mono)",
  fontSize: 12,
  foregroundColor: "#108FFF",
  headerBackgroundColor: "#21222C",
  headerFontSize: 14,
  headerFontWeight: 700,
  headerTextColor: "#108FFF",
  headerVerticalPaddingScale: 1.5,
  oddRowBackgroundColor: "#000000",
  rangeSelectionBackgroundColor: "#108FFF",
  rangeSelectionBorderColor: "#108FFF",
  rangeSelectionBorderStyle: "dashed",
  rowBorder: true,
  rowVerticalPaddingScale: 1.5,
  sidePanelBorder: true,
  spacing: 4,
  wrapperBorder: true,
  wrapperBorderRadius: 0,
})
