# AUTO-GENERATED FILE
# DO NOT EDIT MANUALLY – generated by generate_fake_test_env.py

from uuid import uuid4
from tests.fixtures.fake_db import DB, _find, _insert, _update, _delete


class AlertLogsService:
    def get_all_alert_logs(self, filters=None, limit=1000, page=1):
        return _find("alert_logs", filters or {}, limit)

    def get_alert_logs_by_id(self, id):
        return next((r for r in DB["alert_logs"] if r.get("id") == id), None)

    def create_alert_logs(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("alert_logs", data)

    def update_alert_logs(self, id, payload: dict):
        return _update("alert_logs", id, payload)

    def delete_alert_logs(self, id):
        return _delete("alert_logs", id)

alert_logs_service = AlertLogsService()


class VariationsService:
    def get_all_variations(self, filters=None, limit=1000, page=1):
        return _find("variations", filters or {}, limit)

    def get_variations_by_id(self, id):
        return next((r for r in DB["variations"] if r.get("id") == id), None)

    def create_variations(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("variations", data)

    def update_variations(self, id, payload: dict):
        return _update("variations", id, payload)

    def delete_variations(self, id):
        return _delete("variations", id)

variations_service = VariationsService()


class BillingItemService:
    def get_all_billing_item(self, filters=None, limit=1000, page=1):
        return _find("billing_item", filters or {}, limit)

    def get_billing_item_by_id(self, id):
        return next((r for r in DB["billing_item"] if r.get("id") == id), None)

    def create_billing_item(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("billing_item", data)

    def update_billing_item(self, id, payload: dict):
        return _update("billing_item", id, payload)

    def delete_billing_item(self, id):
        return _delete("billing_item", id)

billing_item_service = BillingItemService()


class MarketSupplierAliasService:
    def get_all_market_supplier_alias(self, filters=None, limit=1000, page=1):
        return _find("market_supplier_alias", filters or {}, limit)

    def get_market_supplier_alias_by_id(self, id):
        return next((r for r in DB["market_supplier_alias"] if r.get("id") == id), None)

    def create_market_supplier_alias(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("market_supplier_alias", data)

    def update_market_supplier_alias(self, id, payload: dict):
        return _update("market_supplier_alias", id, payload)

    def delete_market_supplier_alias(self, id):
        return _delete("market_supplier_alias", id)

market_supplier_alias_service = MarketSupplierAliasService()


class MercurialesService:
    def get_all_mercuriales(self, filters=None, limit=1000, page=1):
        return _find("mercuriales", filters or {}, limit)

    def get_mercuriales_by_id(self, id):
        return next((r for r in DB["mercuriales"] if r.get("id") == id), None)

    def create_mercuriales(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("mercuriales", data)

    def update_mercuriales(self, id, payload: dict):
        return _update("mercuriales", id, payload)

    def delete_mercuriales(self, id):
        return _delete("mercuriales", id)

mercuriales_service = MercurialesService()


class RecommendationsAiService:
    def get_all_recommendations_ai(self, filters=None, limit=1000, page=1):
        return _find("recommendations_ai", filters or {}, limit)

    def get_recommendations_ai_by_id(self, id):
        return next((r for r in DB["recommendations_ai"] if r.get("id") == id), None)

    def create_recommendations_ai(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("recommendations_ai", data)

    def update_recommendations_ai(self, id, payload: dict):
        return _update("recommendations_ai", id, payload)

    def delete_recommendations_ai(self, id):
        return _delete("recommendations_ai", id)

recommendations_ai_service = RecommendationsAiService()


class MaintenanceService:
    def get_all_maintenance(self, filters=None, limit=1000, page=1):
        return _find("maintenance", filters or {}, limit)

    def get_maintenance_by_id(self, id):
        return next((r for r in DB["maintenance"] if r.get("id") == id), None)

    def create_maintenance(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("maintenance", data)

    def update_maintenance(self, id, payload: dict):
        return _update("maintenance", id, payload)

    def delete_maintenance(self, id):
        return _delete("maintenance", id)

maintenance_service = MaintenanceService()


class HistoryRecipesService:
    def get_all_history_recipes(self, filters=None, limit=1000, page=1):
        return _find("history_recipes", filters or {}, limit)

    def get_history_recipes_by_id(self, id):
        return next((r for r in DB["history_recipes"] if r.get("id") == id), None)

    def create_history_recipes(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("history_recipes", data)

    def update_history_recipes(self, id, payload: dict):
        return _update("history_recipes", id, payload)

    def delete_history_recipes(self, id):
        return _delete("history_recipes", id)

history_recipes_service = HistoryRecipesService()


class MarketMasterArticlesService:
    def get_all_market_master_articles(self, filters=None, limit=1000, page=1):
        return _find("market_master_articles", filters or {}, limit)

    def get_market_master_articles_by_id(self, id):
        return next((r for r in DB["market_master_articles"] if r.get("id") == id), None)

    def create_market_master_articles(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("market_master_articles", data)

    def update_market_master_articles(self, id, payload: dict):
        return _update("market_master_articles", id, payload)

    def delete_market_master_articles(self, id):
        return _delete("market_master_articles", id)

market_master_articles_service = MarketMasterArticlesService()


class RecipeCategoriesService:
    def get_all_recipe_categories(self, filters=None, limit=1000, page=1):
        return _find("recipe_categories", filters or {}, limit)

    def get_recipe_categories_by_id(self, id):
        return next((r for r in DB["recipe_categories"] if r.get("id") == id), None)

    def create_recipe_categories(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("recipe_categories", data)

    def update_recipe_categories(self, id, payload: dict):
        return _update("recipe_categories", id, payload)

    def delete_recipe_categories(self, id):
        return _delete("recipe_categories", id)

recipe_categories_service = RecipeCategoriesService()


class ImpersonationsPadrinoService:
    def get_all_impersonations_padrino(self, filters=None, limit=1000, page=1):
        return _find("impersonations_padrino", filters or {}, limit)

    def get_impersonations_padrino_by_id(self, id):
        return next((r for r in DB["impersonations_padrino"] if r.get("id") == id), None)

    def create_impersonations_padrino(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("impersonations_padrino", data)

    def update_impersonations_padrino(self, id, payload: dict):
        return _update("impersonations_padrino", id, payload)

    def delete_impersonations_padrino(self, id):
        return _delete("impersonations_padrino", id)

impersonations_padrino_service = ImpersonationsPadrinoService()


class CountriesService:
    def get_all_countries(self, filters=None, limit=1000, page=1):
        return _find("countries", filters or {}, limit)

    def get_countries_by_id(self, id):
        return next((r for r in DB["countries"] if r.get("id") == id), None)

    def create_countries(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("countries", data)

    def update_countries(self, id, payload: dict):
        return _update("countries", id, payload)

    def delete_countries(self, id):
        return _delete("countries", id)

countries_service = CountriesService()


class RegexPatternsService:
    def get_all_regex_patterns(self, filters=None, limit=1000, page=1):
        return _find("regex_patterns", filters or {}, limit)

    def get_regex_patterns_by_id(self, id):
        return next((r for r in DB["regex_patterns"] if r.get("id") == id), None)

    def create_regex_patterns(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("regex_patterns", data)

    def update_regex_patterns(self, id, payload: dict):
        return _update("regex_patterns", id, payload)

    def delete_regex_patterns(self, id):
        return _delete("regex_patterns", id)

regex_patterns_service = RegexPatternsService()


class LiveScoreService:
    def get_all_live_score(self, filters=None, limit=1000, page=1):
        return _find("live_score", filters or {}, limit)

    def get_live_score_by_id(self, id):
        return next((r for r in DB["live_score"] if r.get("id") == id), None)

    def create_live_score(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("live_score", data)

    def update_live_score(self, id, payload: dict):
        return _update("live_score", id, payload)

    def delete_live_score(self, id):
        return _delete("live_score", id)

live_score_service = LiveScoreService()


class HistoryIngredientsService:
    def get_all_history_ingredients(self, filters=None, limit=1000, page=1):
        return _find("history_ingredients", filters or {}, limit)

    def get_history_ingredients_by_id(self, id):
        return next((r for r in DB["history_ingredients"] if r.get("id") == id), None)

    def create_history_ingredients(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("history_ingredients", data)

    def update_history_ingredients(self, id, payload: dict):
        return _update("history_ingredients", id, payload)

    def delete_history_ingredients(self, id):
        return _delete("history_ingredients", id)

history_ingredients_service = HistoryIngredientsService()


class PriceService:
    def get_all_price(self, filters=None, limit=1000, page=1):
        return _find("price", filters or {}, limit)

    def get_price_by_id(self, id):
        return next((r for r in DB["price"] if r.get("id") == id), None)

    def create_price(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("price", data)

    def update_price(self, id, payload: dict):
        return _update("price", id, payload)

    def delete_price(self, id):
        return _delete("price", id)

price_service = PriceService()


class MarketArticlesService:
    def get_all_market_articles(self, filters=None, limit=1000, page=1):
        return _find("market_articles", filters or {}, limit)

    def get_market_articles_by_id(self, id):
        return next((r for r in DB["market_articles"] if r.get("id") == id), None)

    def create_market_articles(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("market_articles", data)

    def update_market_articles(self, id, payload: dict):
        return _update("market_articles", id, payload)

    def delete_market_articles(self, id):
        return _delete("market_articles", id)

market_articles_service = MarketArticlesService()


class MessagesIaService:
    def get_all_messages_ia(self, filters=None, limit=1000, page=1):
        return _find("messages_ia", filters or {}, limit)

    def get_messages_ia_by_id(self, id):
        return next((r for r in DB["messages_ia"] if r.get("id") == id), None)

    def create_messages_ia(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("messages_ia", data)

    def update_messages_ia(self, id, payload: dict):
        return _update("messages_ia", id, payload)

    def delete_messages_ia(self, id):
        return _delete("messages_ia", id)

messages_ia_service = MessagesIaService()


class RecipesService:
    def get_all_recipes(self, filters=None, limit=1000, page=1):
        return _find("recipes", filters or {}, limit)

    def get_recipes_by_id(self, id):
        return next((r for r in DB["recipes"] if r.get("id") == id), None)

    def create_recipes(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("recipes", data)

    def update_recipes(self, id, payload: dict):
        return _update("recipes", id, payload)

    def delete_recipes(self, id):
        return _delete("recipes", id)

recipes_service = RecipesService()


class SuppliersService:
    def get_all_suppliers(self, filters=None, limit=1000, page=1):
        return _find("suppliers", filters or {}, limit)

    def get_suppliers_by_id(self, id):
        return next((r for r in DB["suppliers"] if r.get("id") == id), None)

    def create_suppliers(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("suppliers", data)

    def update_suppliers(self, id, payload: dict):
        return _update("suppliers", id, payload)

    def delete_suppliers(self, id):
        _delete("suppliers", id)
        DB["supplier_alias"] = [
            alias for alias in DB["supplier_alias"] if alias.get("supplier_id") != id
        ]
        return {"deleted": True}

suppliers_service = SuppliersService()


class EstablishmentEmailAliasService:
    def get_all_establishment_email_alias(self, filters=None, limit=1000, page=1):
        return _find("establishment_email_alias", filters or {}, limit)

    def get_establishment_email_alias_by_id(self, id):
        return next((r for r in DB["establishment_email_alias"] if r.get("id") == id), None)

    def create_establishment_email_alias(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("establishment_email_alias", data)

    def update_establishment_email_alias(self, id, payload: dict):
        return _update("establishment_email_alias", id, payload)

    def delete_establishment_email_alias(self, id):
        return _delete("establishment_email_alias", id)

establishment_email_alias_service = EstablishmentEmailAliasService()


class RecipeMarginService:
    def get_all_recipe_margin(self, filters=None, limit=1000, page=1):
        return _find("recipe_margin", filters or {}, limit)

    def get_recipe_margin_by_id(self, id):
        return next((r for r in DB["recipe_margin"] if r.get("id") == id), None)

    def create_recipe_margin(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("recipe_margin", data)

    def update_recipe_margin(self, id, payload: dict):
        return _update("recipe_margin", id, payload)

    def delete_recipe_margin(self, id):
        return _delete("recipe_margin", id)

recipe_margin_service = RecipeMarginService()


class MasterArticlesService:
    def get_all_master_articles(self, filters=None, limit=1000, page=1):
        return _find("master_articles", filters or {}, limit)

    def get_master_articles_by_id(self, id):
        return next((r for r in DB["master_articles"] if r.get("id") == id), None)

    def create_master_articles(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("master_articles", data)

    def update_master_articles(self, id, payload: dict):
        return _update("master_articles", id, payload)

    def delete_master_articles(self, id):
        return _delete("master_articles", id)

master_articles_service = MasterArticlesService()


class UserEstablishmentService:
    def get_all_user_establishment(self, filters=None, limit=1000, page=1):
        return _find("user_establishment", filters or {}, limit)

    def get_user_establishment_by_id(self, id):
        return next((r for r in DB["user_establishment"] if r.get("id") == id), None)

    def create_user_establishment(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("user_establishment", data)

    def update_user_establishment(self, id, payload: dict):
        return _update("user_establishment", id, payload)

    def delete_user_establishment(self, id):
        return _delete("user_establishment", id)

user_establishment_service = UserEstablishmentService()


class RecipesSubcategoriesService:
    def get_all_recipes_subcategories(self, filters=None, limit=1000, page=1):
        return _find("recipes_subcategories", filters or {}, limit)

    def get_recipes_subcategories_by_id(self, id):
        return next((r for r in DB["recipes_subcategories"] if r.get("id") == id), None)

    def create_recipes_subcategories(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("recipes_subcategories", data)

    def update_recipes_subcategories(self, id, payload: dict):
        return _update("recipes_subcategories", id, payload)

    def delete_recipes_subcategories(self, id):
        return _delete("recipes_subcategories", id)

recipes_subcategories_service = RecipesSubcategoriesService()


class SupportTicketService:
    def get_all_support_ticket(self, filters=None, limit=1000, page=1):
        return _find("support_ticket", filters or {}, limit)

    def get_support_ticket_by_id(self, id):
        return next((r for r in DB["support_ticket"] if r.get("id") == id), None)

    def create_support_ticket(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("support_ticket", data)

    def update_support_ticket(self, id, payload: dict):
        return _update("support_ticket", id, payload)

    def delete_support_ticket(self, id):
        return _delete("support_ticket", id)

support_ticket_service = SupportTicketService()


class LogsIaService:
    def get_all_logs_ia(self, filters=None, limit=1000, page=1):
        return _find("logs_ia", filters or {}, limit)

    def get_logs_ia_by_id(self, id):
        return next((r for r in DB["logs_ia"] if r.get("id") == id), None)

    def create_logs_ia(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("logs_ia", data)

    def update_logs_ia(self, id, payload: dict):
        return _update("logs_ia", id, payload)

    def delete_logs_ia(self, id):
        return _delete("logs_ia", id)

logs_ia_service = LogsIaService()


class PriceStripeService:
    def get_all_price_stripe(self, filters=None, limit=1000, page=1):
        return _find("price_stripe", filters or {}, limit)

    def get_price_stripe_by_id(self, id):
        return next((r for r in DB["price_stripe"] if r.get("id") == id), None)

    def create_price_stripe(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("price_stripe", data)

    def update_price_stripe(self, id, payload: dict):
        return _update("price_stripe", id, payload)

    def delete_price_stripe(self, id):
        return _delete("price_stripe", id)

price_stripe_service = PriceStripeService()


class UserProfilesService:
    def get_all_user_profiles(self, filters=None, limit=1000, page=1):
        return _find("user_profiles", filters or {}, limit)

    def get_user_profiles_by_id(self, id):
        return next((r for r in DB["user_profiles"] if r.get("id") == id), None)

    def create_user_profiles(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("user_profiles", data)

    def update_user_profiles(self, id, payload: dict):
        return _update("user_profiles", id, payload)

    def delete_user_profiles(self, id):
        return _delete("user_profiles", id)

user_profiles_service = UserProfilesService()


class BillingAccountService:
    def get_all_billing_account(self, filters=None, limit=1000, page=1):
        return _find("billing_account", filters or {}, limit)

    def get_billing_account_by_id(self, id):
        return next((r for r in DB["billing_account"] if r.get("id") == id), None)

    def create_billing_account(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("billing_account", data)

    def update_billing_account(self, id, payload: dict):
        return _update("billing_account", id, payload)

    def delete_billing_account(self, id):
        return _delete("billing_account", id)

billing_account_service = BillingAccountService()


class LabelSupplierService:
    def get_all_label_supplier(self, filters=None, limit=1000, page=1):
        return _find("label_supplier", filters or {}, limit)

    def get_label_supplier_by_id(self, id):
        return next((r for r in DB["label_supplier"] if r.get("id") == id), None)

    def create_label_supplier(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("label_supplier", data)

    def update_label_supplier(self, id, payload: dict):
        return _update("label_supplier", id, payload)

    def delete_label_supplier(self, id):
        return _delete("label_supplier", id)

label_supplier_service = LabelSupplierService()


class RecipeMarginSubcategoryService:
    def get_all_recipe_margin_subcategory(self, filters=None, limit=1000, page=1):
        return _find("recipe_margin_subcategory", filters or {}, limit)

    def get_recipe_margin_subcategory_by_id(self, id):
        return next((r for r in DB["recipe_margin_subcategory"] if r.get("id") == id), None)

    def create_recipe_margin_subcategory(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("recipe_margin_subcategory", data)

    def update_recipe_margin_subcategory(self, id, payload: dict):
        return _update("recipe_margin_subcategory", id, payload)

    def delete_recipe_margin_subcategory(self, id):
        return _delete("recipe_margin_subcategory", id)

recipe_margin_subcategory_service = RecipeMarginSubcategoryService()


class ProductStripeService:
    def get_all_product_stripe(self, filters=None, limit=1000, page=1):
        return _find("product_stripe", filters or {}, limit)

    def get_product_stripe_by_id(self, id):
        return next((r for r in DB["product_stripe"] if r.get("id") == id), None)

    def create_product_stripe(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("product_stripe", data)

    def update_product_stripe(self, id, payload: dict):
        return _update("product_stripe", id, payload)

    def delete_product_stripe(self, id):
        return _delete("product_stripe", id)

product_stripe_service = ProductStripeService()


class LogsService:
    def get_all_logs(self, filters=None, limit=1000, page=1):
        return _find("logs", filters or {}, limit)

    def get_logs_by_id(self, id):
        return next((r for r in DB["logs"] if r.get("id") == id), None)

    def create_logs(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("logs", data)

    def update_logs(self, id, payload: dict):
        return _update("logs", id, payload)

    def delete_logs(self, id):
        return _delete("logs", id)

logs_service = LogsService()


class ScoreMatrixService:
    def get_all_score_matrix(self, filters=None, limit=1000, page=1):
        return _find("score_matrix", filters or {}, limit)

    def get_score_matrix_by_id(self, id):
        return next((r for r in DB["score_matrix"] if r.get("id") == id), None)

    def create_score_matrix(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("score_matrix", data)

    def update_score_matrix(self, id, payload: dict):
        return _update("score_matrix", id, payload)

    def delete_score_matrix(self, id):
        return _delete("score_matrix", id)

score_matrix_service = ScoreMatrixService()


class MercurialeArticlesService:
    def get_all_mercuriale_articles(self, filters=None, limit=1000, page=1):
        return _find("mercuriale_articles", filters or {}, limit)

    def get_mercuriale_articles_by_id(self, id):
        return next((r for r in DB["mercuriale_articles"] if r.get("id") == id), None)

    def create_mercuriale_articles(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("mercuriale_articles", data)

    def update_mercuriale_articles(self, id, payload: dict):
        return _update("mercuriale_articles", id, payload)

    def delete_mercuriale_articles(self, id):
        return _delete("mercuriale_articles", id)

mercuriale_articles_service = MercurialeArticlesService()


class VatRatesService:
    def get_all_vat_rates(self, filters=None, limit=1000, page=1):
        return _find("vat_rates", filters or {}, limit)

    def get_vat_rates_by_id(self, id):
        return next((r for r in DB["vat_rates"] if r.get("id") == id), None)

    def create_vat_rates(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("vat_rates", data)

    def update_vat_rates(self, id, payload: dict):
        return _update("vat_rates", id, payload)

    def delete_vat_rates(self, id):
        return _delete("vat_rates", id)

vat_rates_service = VatRatesService()


class FinancialRecipesService:
    def get_all_financial_recipes(self, filters=None, limit=1000, page=1):
        return _find("financial_recipes", filters or {}, limit)

    def get_financial_recipes_by_id(self, id):
        return next((r for r in DB["financial_recipes"] if r.get("id") == id), None)

    def create_financial_recipes(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("financial_recipes", data)

    def update_financial_recipes(self, id, payload: dict):
        return _update("financial_recipes", id, payload)

    def delete_financial_recipes(self, id):
        return _delete("financial_recipes", id)

financial_recipes_service = FinancialRecipesService()


class SupplierMergeSuggestionsService:
    def get_all_supplier_merge_suggestions(self, filters=None, limit=1000, page=1):
        return _find("supplier_merge_suggestions", filters or {}, limit)

    def get_supplier_merge_suggestions_by_id(self, id):
        return next((r for r in DB["supplier_merge_suggestions"] if r.get("id") == id), None)

    def create_supplier_merge_suggestions(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("supplier_merge_suggestions", data)

    def update_supplier_merge_suggestions(self, id, payload: dict):
        return _update("supplier_merge_suggestions", id, payload)

    def delete_supplier_merge_suggestions(self, id):
        return _delete("supplier_merge_suggestions", id)

supplier_merge_suggestions_service = SupplierMergeSuggestionsService()


class SupplierAliasService:
    def get_all_supplier_alias(self, filters=None, limit=1000, page=1):
        return _find("supplier_alias", filters or {}, limit)

    def get_supplier_alias_by_id(self, id):
        return next((r for r in DB["supplier_alias"] if r.get("id") == id), None)

    def create_supplier_alias(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("supplier_alias", data)

    def update_supplier_alias(self, id, payload: dict):
        return _update("supplier_alias", id, payload)

    def delete_supplier_alias(self, id):
        return _delete("supplier_alias", id)

supplier_alias_service = SupplierAliasService()


class UsageCountersService:
    def get_all_usage_counters(self, filters=None, limit=1000, page=1):
        return _find("usage_counters", filters or {}, limit)

    def get_usage_counters_by_id(self, id):
        return next((r for r in DB["usage_counters"] if r.get("id") == id), None)

    def create_usage_counters(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("usage_counters", data)

    def update_usage_counters(self, id, payload: dict):
        return _update("usage_counters", id, payload)

    def delete_usage_counters(self, id):
        return _delete("usage_counters", id)

usage_counters_service = UsageCountersService()


class SessionsIaService:
    def get_all_sessions_ia(self, filters=None, limit=1000, page=1):
        return _find("sessions_ia", filters or {}, limit)

    def get_sessions_ia_by_id(self, id):
        return next((r for r in DB["sessions_ia"] if r.get("id") == id), None)

    def create_sessions_ia(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("sessions_ia", data)

    def update_sessions_ia(self, id, payload: dict):
        return _update("sessions_ia", id, payload)

    def delete_sessions_ia(self, id):
        return _delete("sessions_ia", id)

sessions_ia_service = SessionsIaService()


class IngredientsService:
    def get_all_ingredients(self, filters=None, limit=1000, page=1):
        return _find("ingredients", filters or {}, limit)

    def get_ingredients_by_id(self, id):
        return next((r for r in DB["ingredients"] if r.get("id") == id), None)

    def create_ingredients(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("ingredients", data)

    def update_ingredients(self, id, payload: dict):
        return _update("ingredients", id, payload)

    def delete_ingredients(self, id):
        return _delete("ingredients", id)

ingredients_service = IngredientsService()


class ProductService:
    def get_all_product(self, filters=None, limit=1000, page=1):
        return _find("product", filters or {}, limit)

    def get_product_by_id(self, id):
        return next((r for r in DB["product"] if r.get("id") == id), None)

    def create_product(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("product", data)

    def update_product(self, id, payload: dict):
        return _update("product", id, payload)

    def delete_product(self, id):
        return _delete("product", id)

product_service = ProductService()


class FinancialIngredientsService:
    def get_all_financial_ingredients(self, filters=None, limit=1000, page=1):
        return _find("financial_ingredients", filters or {}, limit)

    def get_financial_ingredients_by_id(self, id):
        return next((r for r in DB["financial_ingredients"] if r.get("id") == id), None)

    def create_financial_ingredients(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("financial_ingredients", data)

    def update_financial_ingredients(self, id, payload: dict):
        return _update("financial_ingredients", id, payload)

    def delete_financial_ingredients(self, id):
        return _delete("financial_ingredients", id)

financial_ingredients_service = FinancialIngredientsService()


class RecipeMarginCategoryService:
    def get_all_recipe_margin_category(self, filters=None, limit=1000, page=1):
        return _find("recipe_margin_category", filters or {}, limit)

    def get_recipe_margin_category_by_id(self, id):
        return next((r for r in DB["recipe_margin_category"] if r.get("id") == id), None)

    def create_recipe_margin_category(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("recipe_margin_category", data)

    def update_recipe_margin_category(self, id, payload: dict):
        return _update("recipe_margin_category", id, payload)

    def delete_recipe_margin_category(self, id):
        return _delete("recipe_margin_category", id)

recipe_margin_category_service = RecipeMarginCategoryService()


class MarketSuppliersService:
    def get_all_market_suppliers(self, filters=None, limit=1000, page=1):
        return _find("market_suppliers", filters or {}, limit)

    def get_market_suppliers_by_id(self, id):
        return next((r for r in DB["market_suppliers"] if r.get("id") == id), None)

    def create_market_suppliers(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("market_suppliers", data)

    def update_market_suppliers(self, id, payload: dict):
        return _update("market_suppliers", id, payload)

    def delete_market_suppliers(self, id):
        return _delete("market_suppliers", id)

market_suppliers_service = MarketSuppliersService()


class ArticlesService:
    def get_all_articles(self, filters=None, limit=1000, page=1):
        return _find("articles", filters or {}, limit)

    def get_articles_by_id(self, id):
        return next((r for r in DB["articles"] if r.get("id") == id), None)

    def create_articles(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("articles", data)

    def update_articles(self, id, payload: dict):
        return _update("articles", id, payload)

    def delete_articles(self, id):
        return _delete("articles", id)

articles_service = ArticlesService()


class EstablishmentsService:
    def get_all_establishments(self, filters=None, limit=1000, page=1):
        return _find("establishments", filters or {}, limit)

    def get_establishments_by_id(self, id):
        return next((r for r in DB["establishments"] if r.get("id") == id), None)

    def create_establishments(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("establishments", data)

    def update_establishments(self, id, payload: dict):
        return _update("establishments", id, payload)

    def delete_establishments(self, id):
        return _delete("establishments", id)

establishments_service = EstablishmentsService()


class UserMercurialeAccessService:
    def get_all_user_mercuriale_access(self, filters=None, limit=1000, page=1):
        return _find("user_mercuriale_access", filters or {}, limit)

    def get_user_mercuriale_access_by_id(self, id):
        return next((r for r in DB["user_mercuriale_access"] if r.get("id") == id), None)

    def create_user_mercuriale_access(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("user_mercuriale_access", data)

    def update_user_mercuriale_access(self, id, payload: dict):
        return _update("user_mercuriale_access", id, payload)

    def delete_user_mercuriale_access(self, id):
        return _delete("user_mercuriale_access", id)

user_mercuriale_access_service = UserMercurialeAccessService()


class InvoicesRejectedService:
    def get_all_invoices_rejected(self, filters=None, limit=1000, page=1):
        return _find("invoices_rejected", filters or {}, limit)

    def get_invoices_rejected_by_id(self, id):
        return next((r for r in DB["invoices_rejected"] if r.get("id") == id), None)

    def create_invoices_rejected(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("invoices_rejected", data)

    def update_invoices_rejected(self, id, payload: dict):
        return _update("invoices_rejected", id, payload)

    def delete_invoices_rejected(self, id):
        return _delete("invoices_rejected", id)

invoices_rejected_service = InvoicesRejectedService()


class ImportJobService:
    def get_all_import_job(self, filters=None, limit=1000, page=1):
        return _find("import_job", filters or {}, limit)

    def get_import_job_by_id(self, id):
        return next((r for r in DB["import_job"] if r.get("id") == id), None)

    def create_import_job(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("import_job", data)

    def update_import_job(self, id, payload: dict):
        return _update("import_job", id, payload)

    def delete_import_job(self, id):
        return _delete("import_job", id)

import_job_service = ImportJobService()


class InvoicesService:
    def get_all_invoices(self, filters=None, limit=1000, page=1):
        return _find("invoices", filters or {}, limit)

    def get_invoices_by_id(self, id):
        return next((r for r in DB["invoices"] if r.get("id") == id), None)

    def create_invoices(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("invoices", data)

    def update_invoices(self, id, payload: dict):
        return _update("invoices", id, payload)

    def delete_invoices(self, id):
        return _delete("invoices", id)

invoices_service = InvoicesService()


class FinancialReportsService:
    def get_all_financial_reports(self, filters=None, limit=1000, page=1):
        return _find("financial_reports", filters or {}, limit)

    def get_financial_reports_by_id(self, id):
        return next((r for r in DB["financial_reports"] if r.get("id") == id), None)

    def create_financial_reports(self, payload: dict):
        data = dict(payload)
        if "id" not in data:
            data["id"] = uuid4()
        return _insert("financial_reports", data)

    def update_financial_reports(self, id, payload: dict):
        return _update("financial_reports", id, payload)

    def delete_financial_reports(self, id):
        return _delete("financial_reports", id)

financial_reports_service = FinancialReportsService()
