# AUTO-GENERATED FILE
# DO NOT EDIT MANUALLY – generated by generate_fake_test_env.py

from uuid import uuid4
from typing import Dict, Any
from datetime import datetime, date
import uuid as uuid_mod

DB = {
    "messages_ia": [],
    "establishments": [],
    "recommendations_ai": [],
    "mercuriale_categories": [],
    "countries": [],
    "market_master_articles": [],
    "supplier_merge_request": [],
    "market_supplier_alias": [],
    "mercuriale_supplier": [],
    "score_matrix": [],
    "live_score": [],
    "vat_rates": [],
    "supplier_merge_suggestions": [],
    "impersonations_padrino": [],
    "alert_logs": [],
    "maintenance": [],
    "logs_ia": [],
    "master_articles": [],
    "support_ticket": [],
    "market_articles": [],
    "recipe_margin_subcategory": [],
    "billing_account": [],
    "mercuriale_articles": [],
    "user_profiles": [],
    "financial_ingredients": [],
    "mercuriale_subcategories": [],
    "sessions_ia": [],
    "invoices_rejected": [],
    "financial_reports": [],
    "price_stripe": [],
    "financial_recipes": [],
    "product_stripe": [],
    "billing_item": [],
    "market_suppliers": [],
    "usage_counters": [],
    "mercuriale_master_article": [],
    "logs": [],
    "user_mercuriale_access": [],
    "recipes": [],
    "recipes_subcategories": [],
    "establishment_email_alias": [],
    "import_job": [],
    "recipe_categories": [],
    "history_ingredients": [],
    "articles": [],
    "user_establishment": [],
    "invoices": [],
    "suppliers": [],
    "mercurial_request": [],
    "supplier_alias": [],
    "variations": [],
    "history_recipes": [],
    "mercuriales": [],
    "recipe_margin_category": [],
    "ingredients": [],
    "recipe_margin": [],
    "regex_patterns": [],
}

def reset_db():
    for key in DB:
        DB[key] = []


def _normalize(x):
    if isinstance(x, uuid_mod.UUID):
        return str(x)
    if isinstance(x, datetime):
        return x.date()
    if isinstance(x, date):
        return x
    if isinstance(x, str) and len(x) == 10 and x.count("-") == 2:
        try:
            return datetime.fromisoformat(x).date()
        except Exception:
            return x
    return x

def _find(table: str, filters=None, limit=1000):
    if filters is None:
        filters = {}
    out = []
    for row in DB[table]:
        ok = True
        for k, v in filters.items():
            if v is None:
                continue
            if k in ("order_by", "direction", "limit", "page"):
                continue

            if k.endswith("_lte"):
                base = k[:-4]
                rv = _normalize(row.get(base))
                fv = _normalize(v)
                if rv is None or rv > fv:
                    ok = False
                    break
                continue

            if k.endswith("_gte"):
                base = k[:-4]
                rv = _normalize(row.get(base))
                fv = _normalize(v)
                if rv is None or rv < fv:
                    ok = False
                    break
                continue

            if k.endswith("_neq"):
                base = k[:-4]
                rv = _normalize(row.get(base))
                fv = _normalize(v)
                if rv == fv:
                    ok = False
                    break
                continue

            if k.endswith("_like"):
                base = k[:-5]
                rv = row.get(base)
                if rv is None or str(v).strip("%") not in str(rv):
                    ok = False
                    break
                continue

            if _normalize(row.get(k)) != _normalize(v):
                ok = False
                break

        if ok:
            out.append(row)

    order_by = filters.get("order_by")
    direction = filters.get("direction")

    if order_by:
        out.sort(
            key=lambda r: _normalize(r.get(order_by)),
            reverse=(direction == "desc")
        )

    return out[:limit]


def _insert(table: str, data: Dict[str, Any]):
    DB[table].append(data)
    return data


def _update(table: str, id, payload: Dict[str, Any]):
    for row in DB[table]:
        if row.get("id") == id:
            row.update(payload)
            return row
    return None


def _delete(table: str, id):
    DB[table] = [r for r in DB[table] if r.get("id") != id]
    return {"deleted": True}

# --- HELPERS AUTO-GÉNÉRÉS ---

def create_messages_ia(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("messages_ia", data)

def create_establishments(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("establishments", data)

def create_recommendations_ai(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("recommendations_ai", data)

def create_mercuriale_categories(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("mercuriale_categories", data)

def create_countries(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("countries", data)

def create_market_master_articles(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("market_master_articles", data)

def create_supplier_merge_request(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("supplier_merge_request", data)

def create_market_supplier_alias(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("market_supplier_alias", data)

def create_mercuriale_supplier(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("mercuriale_supplier", data)

def create_score_matrix(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("score_matrix", data)

def create_live_score(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("live_score", data)

def create_vat_rates(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("vat_rates", data)

def create_supplier_merge_suggestions(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("supplier_merge_suggestions", data)

def create_impersonations_padrino(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("impersonations_padrino", data)

def create_alert_logs(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("alert_logs", data)

def create_maintenance(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("maintenance", data)

def create_logs_ia(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("logs_ia", data)

def create_master_articles(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("master_articles", data)

def create_support_ticket(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("support_ticket", data)

def create_market_articles(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("market_articles", data)

def create_recipe_margin_subcategory(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("recipe_margin_subcategory", data)

def create_billing_account(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("billing_account", data)

def create_mercuriale_articles(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("mercuriale_articles", data)

def create_user_profiles(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("user_profiles", data)

def create_financial_ingredients(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("financial_ingredients", data)

def create_mercuriale_subcategories(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("mercuriale_subcategories", data)

def create_sessions_ia(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("sessions_ia", data)

def create_invoices_rejected(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("invoices_rejected", data)

def create_financial_reports(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("financial_reports", data)

def create_price_stripe(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("price_stripe", data)

def create_financial_recipes(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("financial_recipes", data)

def create_product_stripe(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("product_stripe", data)

def create_billing_item(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("billing_item", data)

def create_market_suppliers(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("market_suppliers", data)

def create_usage_counters(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("usage_counters", data)

def create_mercuriale_master_article(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("mercuriale_master_article", data)

def create_logs(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("logs", data)

def create_user_mercuriale_access(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("user_mercuriale_access", data)

def create_recipes(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("recipes", data)

def create_recipes_subcategories(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("recipes_subcategories", data)

def create_establishment_email_alias(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("establishment_email_alias", data)

def create_import_job(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("import_job", data)

def create_recipe_categories(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("recipe_categories", data)

def create_history_ingredients(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("history_ingredients", data)

def create_articles(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("articles", data)

def create_user_establishment(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("user_establishment", data)

def create_invoices(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("invoices", data)

def create_suppliers(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("suppliers", data)

def create_mercurial_request(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("mercurial_request", data)

def create_supplier_alias(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("supplier_alias", data)

def create_variations(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("variations", data)

def create_history_recipes(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("history_recipes", data)

def create_mercuriales(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("mercuriales", data)

def create_recipe_margin_category(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("recipe_margin_category", data)

def create_ingredients(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("ingredients", data)

def create_recipe_margin(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("recipe_margin", data)

def create_regex_patterns(data: Dict[str, Any]):
    if "id" not in data:
        data["id"] = uuid4()
    return _insert("regex_patterns", data)
